### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable (View: laravel\resources\views\auth\login.blade.php)

### ISSUE THREAD

**Issue by yassersharaf** [captcha-com/laravel-captcha#5]
Hi,

I'm started using PHP 7.2 and upgraded frpm Laravel 5.4 to laravel 5.6

in composer.json

"captcha-com/laravel-captcha": "4.2.3",

composer update

since then I get this error

laravel\vendor\captcha-com\captcha\lib\botdetect\CaptchaIncludes.php

count(): Parameter must be an array or an object that implements Countable (View: laravel\resources\views\auth\login.blade.php)

How to solve this please?

**Comment by botdetect-support** [comment]
Thanks for bringing this to our attention.

We have confirmed & fixed the issue. The fix will be released with the latest minor update that is expected to be released within the month.

If you own the paid BotDetect license, please write us to support at captcha.com to get the latest build before the official release.

Thanks again,
BotDetect Support

**Comment by neutronstein** [comment]
Hi,
This issue seems to have not been resolved. I've updated to 4.2.4 but no luck.

**Comment by botdetect-support** [comment]
The fix is not yet released - but it is expected to be soon.

If you own the paid BotDetect license, please write us to support at captcha.com to get the latest build before the official release.

Thanks again,
BotDetect Support

**Comment by botdetect-support** [comment]
The fix for issue described above is released now. Please update:
https://packagist.org/packages/captcha-com/laravel-captcha (to v4.2.5)
and
https://packagist.org/packages/captcha-com/captcha (to v4.2.3)

Hope this helps. Let us know if you need anything else.

**Comment by yassersharaf** [comment]
Hi

I've installed v 4.2.5 but captcha.php is not in the config folder

php artisan vendor:publish

it asks me which package to publish (Laravel 5.6) I choose config but
nothing happens (the captcha package is not in the list)

Hope to solve this ASAP.

Regards
